**Problem Statement 1:**
Write a function so that the columns of the output matrix are powers of the input vector. 

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N-i-1.

**Hint:** Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [8]:
import numpy as np
x = np.array([1, 2, 3, 4])
N=3
##using column_stack, the i-th output column is the input vector raised element-wise to the power of N-i-1
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]], dtype=int32)

In [11]:
## using vander function. By default, increasing=False
N = 4
np.vander(x, N)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [13]:
#while increasing=True
np.vander(x, increasing=True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

**Problem Statement 2:**

Given a sequence of n values x1,x2, ...., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

	i   1	2	3	4	5	6	7	8	9	10
===== ==  ==    ==	==	==	==	==	==	==	==

Input	   10	20	30	40	50	60	70	80	90	100

y1	   25=(10+20+30+40)/4	

y2	   35=(20+30+40+50)/4

y3	   45=(30+40+50+60)/4

y4	   55=(40+50+60+70)/4

y5	   65=(50+60+70+80)/4

y6	   75=(60+70+80+90)/4

y7	   85=(70+80+90+100)/4


Thus the moving average sequence has n-k+1=10-4+1 = 7 values.


**Question:** Write a function to find moving average in an array over a window: 

Test it over [3,5,7,2,8,10,11,65,72,81,99,100,150] and window of 3.


In [22]:
def findMovingAverage(a, n) :
    result = np.cumsum(a, dtype=float)
    result[n:] = result[n:] - result[:-n]
    return result[n - 1:] / n

a = np.array([3,5,7,2,8,10,11,65,72,81,99,100,150])
window = 3
findMovingAverage(a, window)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])